apiVersion: v1
kind: Service
metadata:
  name: sts-app-service
  namespace: testing
spec:
  selector:
    app: sts-app
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8081
  type: LoadBalancer
